name = 'En contrucción'
port = 7788
players = 2500
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'RP'
website = 'example.com'
language = 'es'
description = 'alt:V Sample Server'
modules = ['js-module']
resources = ['chat']